# -*- coding: utf-8 -*-
"""Copy of 📚 Lesson - Lists

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ZfSf_Vw6NWIQxvGGdNZVXTReTCpiuer

<div>
<img src="https://coursereport-s3-production.global.ssl.fastly.net/uploads/school/logo/219/original/CT_LOGO_NEW.jpg" width=60>
</div>

#  **Lists**

*Be sure to be following along with the lesson page before progressing in this notebook!*

## **🛝 Practice Playground** - Section 1
In Python, lists are dynamic arrays that can store elements of different types. They are both flexible and easy to use, making them ideal for situations where you need an ordered collection of items. Lists are defined with square brackets [] and can include integers, strings, and even other lists.
"""

# Run this cell!

friends = ["Aaron", "Becky", "Chad", "Dustin", "Eric"]

# Run this cell!

friends[0]

# Run this cell!

friends[1]

# Run this cell!

friends[2]

# Run this cell!

friends[4]

# Run this cell!

friends[-1]

# Run this cell!

friends[0:2]

# Run this cell!

friends[:2]

# Run this cell!

friends[1:]

# Run this cell!

friends[::]

# Run this cell!

friends[1:4:2]

# Run this cell!

friends[::-1]

"""## **🛝 Practice Playground** - Section 2
Lists in Python are dynamic arrays that can easily be modified. This flexibility is a significant advantage when managing collections of data where modifications are frequent. Whether you're adding elements, removing them, or altering existing entries, Python lists offer a range of methods to handle these operations efficiently. This section will guide you through various techniques to modify lists, illustrating how to effectively utilize Python's capabilities to manipulate list contents. We’ll explore adding, removing, and altering elements, ensuring you have a comprehensive understanding of how to interact with list data dynamically.
"""

# Run this cell!

# This modifies the list in place, and therefore does not return the updated list as an output.

friends.append("Katie")

# Run this cell!

# To see the updated list, simply run the cell containing friends after making
# changes. This will display the current state of the list.

friends

# Run this cell!

# This modifies the list in place, and therefore does not return the updated list as an output.

friends.insert(1, "Jennifer")

# Run this cell!

# To see the updated list, simply run the cell containing friends after making
# changes. This will display the current state of the list.

friends

# Run this cell!

friends[0] = "Kevin"

# Run this cell!

# To see the updated list, simply run the cell containing friends after making
# changes. This will display the current state of the list.

friends

# Run this cell!

# This modifies the list in place, and therefore does not return the updated list as an output.


friends.remove("Katie")

# Run this cell!

# To see the updated list, simply run the cell containing friends after making
# changes. This will display the current state of the list.

friends

"""---

## **🛝 Practice Playground** - Section 3
Lists are one of the most versatile data structures in Python, equipped with a multitude of methods for manipulating their contents. Understanding these methods can significantly enhance your ability to work with lists effectively! You have seen some of these methods previously, but this section will explore the key methods for list manipulation, providing detailed examples to illustrate their use in real-world scenarios.
"""

# Run this cell!

colors = ['red', 'blue', 'green']

# Run this cell!

colors.append('yellow')

# Run this cell!

# To see the updated list, simply run the cell containing colors after making
# changes. This will display the current state of the list.

colors

# Run this cell!

more_colors = ['orange', 'purple']
colors.extend(more_colors)

# Run this cell!

# To see the updated list, simply run the cell containing colors after making
# changes. This will display the current state of the list.

colors

# Run this cell!

colors.insert(3, 'black')

# Run this cell!

# To see the updated list, simply run the cell containing colors after making
# changes. This will display the current state of the list.

colors

# Run this cell!

colors.remove('black')

# Run this cell!

# To see the updated list, simply run the cell containing colors after making
# changes. This will display the current state of the list.

colors

# Run this cell!

colors.index('purple')

# Run this cell!

colors.count('blue')

# Run this cell!

colors.append('blue')

# Run this cell!

colors

# Run this cell!

colors.count('blue')

# Run this cell!

numbers = [3, 1, 4, 1, 5, 9, 2]

# Run this cell!

numbers.sort()

# Run this cell!

numbers

# Run this cell!

numbers.reverse()

# Run this cell!

numbers

# Run this cell!

movies = ['Avatar', 'Interstellar', 'Se7en', 'Inception', 'Barbie']

# Run this cell!

len(movies)

# Run this cell!

exam_scores = [99, 80, 72, 50, 100, 98, 84, 83, 91, 75, 76, 63, 87, 90]

# Run this cell!

sorted_exam_scores = sorted(exam_scores)
sorted_exam_scores

# Run this cell!

sum(exam_scores)

# Run this cell!

max(exam_scores)

# Run this cell!

min(exam_scores)

# Run this cell!

len(exam_scores)

# Run this cell!

average = sum(exam_scores) / len(exam_scores)
average

"""## **🛝 Practice Playground** - Section 4

Nested lists are a powerful feature in Python that allow you to create complex data structures, such as matrices or multi-dimensional arrays. Here’s a detailed look at how to work with a nested list, particularly how to access elements within inner lists.
"""

# Run this cell!

nested_list = [1, [2, 3], [4, [5, 6]], 7]

# Run this cell!

nested_list[2]

# Run this cell!

nested_list[2][1]

# Run this cell!

nested_list[2][1][1]